platform :ios, '8.0'

target 'KKJSBridgeDemo' do
  
  # 默认是 ajax protocol hook
  pod 'KKJSBridge/AjaxProtocolHook', :path => '../'
  
#  pod 'KKJSBridge/AjaxHook', :path => '../'
  pod 'AFNetworking'

end
